name: terraform ansible CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.1.7"
      - id: install-aws-cli
        uses: unfor19/install-aws-cli-action@v1
      - run: mkdir -p ~/.aws
      - run: echo "$super_secret" > ~/.aws/credentials
        env: # Or as an environment variable
          super_secret: ${{ secrets.AWS_CONFIG }}
      - run: cat ~/.aws/credentials
      - run: aws configure list-profiles
      - run: terraform version
      - run: terraform -chdir=./infra init
      - run: terraform -chdir=./infra validate
      - run: terraform -chdir=./infra apply -auto-approve