name: terraform ansible CI

on: [push]

jobs:
  terraform:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.1.7"
      - id: install-aws-cli
        uses: unfor19/install-aws-cli-action@v1
      - run: mkdir -p ~/.aws
      - run: echo "$super_secret" > ~/.aws/credentials
        env: # Or as an environment variable
          super_secret: ${{ secrets.AWS_CONFIG }}
      - run: cat ~/.aws/credentials
      - run: aws configure list-profiles
      - run: terraform version
      - run: terraform -chdir=./infra init
      - run: terraform -chdir=./infra validate
      - run: terraform -chdir=./infra apply -auto-approve
      - uses: actions/upload-artifact@v4
        with:
          name: "tf-key.pem"
          path: "./ansible/tf-key.pem"
      - uses: actions/upload-artifact@v4
        with:
          name: "hosts"
          path: "./ansible/hosts"

  ansible:
    runs-on: ubuntu-latest
        
    steps:
      - name: Download Repo
        uses: actions/checkout@v4

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./ansible

      - name: Ansible
        run: ansible --version